---
title: "Developing a digital marketplace for family planning--Pilot randomized encouragement trial"
output:
  html_document:
    toc: false
    toc_float: false
bibliography: refs.bib
csl: vancouver.csl
---

*In 2017-18, our team of researchers from Duke University and Moi University began a pilot study funded by the Duke Global Health Institute to explore the feasibility of a full-scale of [Nivi](https://www.nivi.io/), a digital marketplace for family planning. We created this study website to store all study-related products and data (licensed under the [CC-BY license](https://creativecommons.org/licenses/by/4.0/)).*

* * * 

Pregnancy exposes women to the risk of maternal death, and family planning is an effective tool for preventing death among women who do not want to become pregnant [@bongaarts:2012]. First, by preventing unintended pregnancies, contraception use reduces deaths caused by unsafe abortions. Second, contraception use leads to fewer high-risk pregnancies among adolescents and women over the age of 35. For the 12-month period ending July 2017, contraceptive use across 69 focal countries included in the global initiative FP2020 is estimated to have prevented 84 million unintended pregnancies, averted 26 million unsafe abortions, and saved 125,000 women from maternal deaths [@fp2020:2017]. Voluntary family planning has also been shown to improve newborn health outcomes, advance women's empowerment, and bring socioeconomic benefits through reductions in fertility and population growth [@bongaarts:2012]. 

Yet among the populations that would benefit the most from family planning, uptake remains too low. In the five years that have passed since the FP2020 initiative launched at the London Summit on Family Planning in 2012, an additional 38.8 million women and girls across the 69 focal countries began using a modern method of contraception [@fp2020:2017]. This progress is above historic trends, but substantially off the pace required to meet the goal of adding 120 million new users by 2020. Across these focal countries, 1 out of every 5 married women of reproductive age would like to prevent or delay childbirth but is not using a modern method of contraception.

This indicator is referred to as unmet need for modern contraception, and it represents a measure of access to family planning. In Kenya, for instance, 17.2% of currently married or in-union women of reproductive age [@kenyanationalbureauofstatistics:2015] and 26.4% of sexually active unmarried women [@kenyanationalbureauofstatistics:2014] have an unmet need for family planning. This translates into approximately 1.3 million women in the country who are not using contraception but say they would like to avoid pregnancy.[^numbers] According to the same nationally representative study, millions of others are either unaware of the potential benefits of contraception, misinformed about the full range of modern methods available, or unsatisfied with previous experiences using contraception. Taken together, this presents a promising opportunity to significantly reduce the current unmet need for family planning and to expand the market.

[^numbers]: In the 2014 Kenya DHS, 59.7% of women ages 15 to 49 were classified as married or in-union and 1.9% unmarried but sexually active. The current population of women ages 15 to 49 is approximately 11.8 million. 

Traditional approaches to promoting the take-up of family planning focus on demand generation activities, and supply-side activities, or a mixture of both. Demand generation can include mass media advertising, interpersonal communication, and development approaches such as conditional cash transfer programs. Supply-side interventions often include efforts to improve service access, quality, and cost. A systematic review of 63 published evaluations of family planning interventions concluded that development approaches and supply-side interventions had the most consistent effect on contraceptive use [@mwaikambo:2011], but the overall quality of the evidence was low.

The emergence of digital health tools such as short message service (SMS), interactive voice response, and smartphone applications have created new opportunities to strengthen health systems and promote behavior change [@labrique:2013; @gurman:2012], but the evidence base remains weak. As is the case in non-digital interventions [@mwaikambo:2011], studies of digital health tools have found that it is easier to increase knowledge than it is to achieve behavior change [@johnson:2017]. 

This pilot study represents another effort to promote behavior change through the use of an SMS intervention. Women with an unmet need for family planning in Western Kenya were randomized to receive an encouragement to try an investigational digital health intervention. The objectives of the pilot study were to explore the feasibility of a full-scale trial—in particular the recruitment, encouragement, and follow-up data collection procedures—and to examine the preliminary effect of the intervention on the take-up of contraception.

# References